import { Product } from "./type";

export const product: Product[] = [
  {
    id: 1,
    image: ["/j/1.jpg"],
    price: 5000,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "pink",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 2,
    image: ["/j/2.jpg"],
    price: 3000,
    category: "Junaid-Jamshed",
    size: ["S", "M", "L", "XL"],
    title: "Junaid Jamshed",
    slug: "lightpurple",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    qty: 1,
  },
  {
    id: 3,
    image: ["/j/3.jpg"],
    price: 3999,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "blue",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 4,
    image: ["/j/4.jpg"],
    price: 4699,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "white",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 5,
    image: ["/j/5.jpg"],
    price: 4699,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "red",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 6,
    image: ["/j/6.jpg"],
    price: 3699,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "purplee",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 7,
    image: ["/j/7.jpg"],
    price: 17440,
    category: "Junaid-Jamshed",
    size: ["S", "M", "L", "XL"],
    title: "Junaid Jamshed",
    slug: "green-pink",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    qty: 1,
  },
  {
    id: 8,
    image: ["/j/8.jpg"],
    price: 14360,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "green",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 9,
    image: ["/j/9.jpg"],
    price: 13699,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "darkpink",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 10,
    image: ["/j/10.jpg"],
    price: 6990,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "peach",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 11,
    image: ["/j/11.jpg"],
    price: 5990,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "black",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 12,
    image: ["/j/12.jpg"],
    price: 3699,
    category: "Junaid-Jamshed",
    size: ["S", "M", "L", "XL"],
    title: "Junaid Jamshed",
    slug: "pinkflower",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    qty: 1,
  },
  {
    id: 13,
    image: ["/j/13.jpg"],
    price: 3590,
    category: "Junaid-Jamshed",
    size: ["S", "M", "L", "XL"],
    title: "Junaid Jamshed",
    slug: "blackflower",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    qty: 1,
  },
  {
    id: 14,
    image: ["/j/14.jpg"],
    price: 5290,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "whiteblack",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 15,
    image: ["/j/15.jpg"],
    price: 6290,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "yellow",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 16,
    image: ["/j/16.jpg"],
    price: 6290,
    category: "Junaid-Jamshed",
    title: "Junaid Jamshed",
    slug: "seagreen",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 17,
    image: ["/alkaram/1.jpg"],
    price: 5999,
    category: "Alkaram",
    size: ["S", "M", "L", "XL"],
    title: "Alkaram",
    slug: "kahigreen",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    qty: 1,
  },
  {
    id: 18,
    image: ["/alkaram/2.jpg"],
    price: 4500,
    title: "Alkaram",
    slug: "peachflowers",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    category: "Alkaram",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 19,
    image: ["/alkaram/3.jpg"],
    price: 5500,
    category: "Alkaram",
    size: ["S", "M", "L", "XL"],
    title: "Alkaram",
    slug: "white-yellow",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    qty: 1,
  },
  {
    id: 20,
    image: ["/alkaram/4.jpg"],
    price: 9999,
    category: "Alkaram",
    title: "Alkaram",
    slug: "blackTriangle",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 21,
    image: ["/alkaram/5.jpg"],
    title: "Alkaram",
    slug: "gray-pink",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    price: 7500,
    category: "Alkaram",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 22,
    image: ["/alkaram/6.jpg"],
    price: 8999,
    category: "Alkaram",
    title: "Alkaram",
    slug: "skyblue",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 23,
    image: ["/alkaram/7.jpg"],
    price: 7899,
    category: "Alkaram",
    title: "Alkaram",
    slug: "black-red",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 24,
    image: ["/alkaram/8.jpg"],
    price: 7000,
    title: "Alkaram",
    slug: "offwhite",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    category: "Alkaram",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 25,
    image: ["/alkaram/9.jpg"],
    price: 4000,
    category: "Alkaram",
    title: "Alkaram",
    slug: "multi",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 26,
    image: ["/alkaram/10.jpg"],
    price: 5000,
    category: "Alkaram",
    title: "Alkaram",
    slug: "lightorange",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 27,
    image: ["/alkaram/11.jpg"],
    price: 6999,
    category: "Alkaram",
    size: ["S", "M", "L", "XL"],
    title: "Alkaram",
    slug: "navyblue",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    qty: 1,
  },
  {
    id: 28,
    image: ["/alkaram/12.jpg"],
    price: 8000,
    category: "Alkaram",
    title: "Alkaram",
    slug: "yellow-white",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 29,
    image: ["/alkaram/13.jpg"],
    price: 7500,
    category: "Alkaram",
    size: ["S", "M", "L", "XL"],
    title: "Alkaram",
    slug: "white-mehroon",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    qty: 1,
  },
  {
    id: 30,
    image: ["/alkaram/14.jpg"],
    price: 6500,
    category: "Alkaram",
    title: "Alkaram",
    slug: "yellow-blue",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 31,
    image: ["/alkaram/15.jpg"],
    price: 4000,
    title: "Alkaram",
    slug: "red-blue",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    category: "Alkaram",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 32,
    image: ["/alkaram/16.jpg"],
    price: 3999,
    title: "Alkaram",
    slug: "pinkflowerkurti",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    category: "Alkaram",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 33,
    image: ["/bonanza/1.jpg"],
    price: 6000,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "blue-white",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 34,
    image: ["/bonanza/2.jpg"],
    price: 7000,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "green-black",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 35,
    image: ["/bonanza/3.jpg"],
    price: 4000,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "planegreen",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 36,
    image: ["/bonanza/4.jpg"],
    price: 8000,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "lightgreen",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 37,
    image: ["/bonanza/5.jpg"],
    price: 7000,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "aquablue",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 38,
    image: ["/bonanza/6.jpg"],
    price: 7000,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "planepink",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 39,
    image: ["/bonanza/7.jpg"],
    price: 6000,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "multi-black",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 40,
    image: ["/bonanza/8.jpg"],
    price: 5000,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "lightpeach",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 41,
    image: ["/bonanza/9.jpg"],
    price: 10000,
    title: "Bonanza Satrangi",
    slug: "brown",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    category: "Bonanza-Satrangi",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 42,
    image: ["/bonanza/10.jpg"],
    price: 8999,
    title: "Bonanza Satrangi",
    slug: "blue-pink",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    category: "Bonanza-Satrangi",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 43,
    image: ["/bonanza/11.jpg"],
    price: 6999,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "green-golden",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 44,
    image: ["/bonanza/12.jpg"],
    price: 5000,
    title: "Bonanza Satrangi",
    slug: "gray",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    category: "Bonanza-Satrangi",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 45,
    image: ["/bonanza/13.jpg"],
    price: 8000,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "whitedot",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 46,
    image: ["/bonanza/14.jpg"],
    price: 9999,
    category: "Bonanza-Satrangi",
    title: "Bonanza Satrangi",
    slug: "whiteflower",
    description:
      "Unveil your unique style with Bonanza Satrangi vibrant collections. Trendy, versatile, and crafted for every occasion! Bonanza Satrangi is a vibrant fashion brand offering a diverse range of stylish and affordable clothing, combining modern trends with traditional craftsmanship for every occasion.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 47,
    image: ["/ideas/1.jpg"],
    price: 9000,
    category: "Gul-Ahmed",
    title: "Gul Ahmed",
    slug: "stylishBlue",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 48,
    image: ["/ideas/2.jpg"],
    price: 7000,
    category: "Gul-Ahmed",
    title: "Gul Ahmed",
    slug: "red-white-garara",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 49,
    image: ["/ideas/3.jpg"],
    price: 8000,
    category: "Gul-Ahmed",
    title: "Gul Ahmed",
    slug: "black-garara",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 50,
    image: ["/ideas/4.jpg"],
    price: 5000,
    category: "Gul-Ahmed",
    title: "Gul Ahmed",
    slug: "leavesprint",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 51,
    image: ["/ideas/5.jpg"],
    price: 7000,
    category: "Gul-Ahmed",
    size: ["S", "M", "L", "XL"],
    title: "Gul Ahmed",
    slug: "golden-yellow",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    qty: 1,
  },
  {
    id: 52,
    image: ["/ideas/6.jpg"],
    price: 15000,
    title: "Gul Ahmed",
    slug: "white-garara",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    category: "Gul-Ahmed",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 53,
    image: ["/ideas/7.jpg"],
    price: 12000,
    category: "Gul-Ahmed",
    size: ["S", "M", "L", "XL"],
    title: "Gul Ahmed",
    slug: "stylishpink",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    qty: 1,
  },
  {
    id: 54,
    image: ["/ideas/8.jpg"],
    price: 8000,
    category: "Gul-Ahmed",
    size: ["S", "M", "L", "XL"],
    title: "Gul Ahmed",
    slug: "aquagreen",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    qty: 1,
  },
  {
    id: 55,
    image: ["/ideas/9.jpg"],
    price: 9000,
    title: "Gul Ahmed",
    slug: "whitesuit",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    category: "Gul-Ahmed",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 56,
    image: ["/ideas/10.jpg"],
    price: 8000,
    category: "Gul-Ahmed",
    title: "Gul Ahmed",
    slug: "lightkahi",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 57,
    image: ["/ideas/11.jpg"],
    price: 12000,
    category: "Gul-Ahmed",
    title: "Gul Ahmed",
    slug: "black-kameez",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 58,
    image: ["/ideas/12.jpg"],
    price: 8000,
    category: "Gul-Ahmed",
    title: "Gul Ahmed",
    slug: "brown-yellow",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 59,
    image: ["/ideas/13.jpg"],
    price: 10000,
    category: "Gul-Ahmed",
    title: "Gul Ahmed",
    slug: "shockingpink",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 60,
    image: ["/ideas/14.jpg"],
    price: 8000,
    category: "Gul-Ahmed",
    size: ["S", "M", "L", "XL"],
    title: "Gul Ahmed",
    slug: "darkpurple",
    description:
      "Embrace elegance and tradition with Gul Ahmed premium fabrics. Unmatched quality and timeless designs, perfect for every season! Gul Ahmed is a leading fashion brand known for its premium fabrics and timeless designs, offering a perfect blend of tradition, elegance, and contemporary style for every season.",
    qty: 1,
  },
  {
    id: 61,
    image: ["/limelight/1.jpg"],
    price: 7000,
    category: "Limelight",
    title: "Limelight",
    slug: "brownkurti",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 62,
    image: ["/limelight/2.jpg"],
    price: 7000,
    title: "Limelight",
    slug: "darkpurple-flowers",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 63,
    image: ["/limelight/3.jpg"],
    title: "Limelight",
    slug: "shortkurti",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    price: 8500,
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 64,
    image: ["/limelight/4.jpg"],
    title: "Limelight",
    slug: "aqua-blue",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    price: 5000,
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 65,
    image: ["/limelight/5.jpg"],
    price: 7500,
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    title: "Limelight",
    slug: "grey",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    qty: 1,
  },
  {
    id: 66,
    image: ["/limelight/6.jpg"],
    title: "Limelight",
    slug: "kurti-shirt",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    price: 8000,
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 67,
    image: ["/limelight/7.jpg"],
    title: "Limelight",
    slug: "big-multiflowers",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    price: 10000,
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 68,
    image: ["/limelight/8.jpg"],
    title: "Limelight",
    slug: "blacklines",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    price: 9500,
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 69,
    image: ["/limelight/9.jpg"],
    price: 12000,
    category: "Limelight",
    title: "Limelight",
    slug: "black-karhai",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 70,
    image: ["/limelight/10.jpg"],
    price: 8000,
    title: "Limelight",
    slug: "pink-kurti",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 71,
    image: ["/limelight/11.jpg"],
    title: "Limelight",
    slug: "blue-gray",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    price: 7000,
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 72,
    image: ["/limelight/12.jpg"],
    price: 8000,
    title: "Limelight",
    slug: "blackfrock",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 73,
    image: ["/limelight/13.jpg"],
    price: 7000,
    title: "Limelight",
    slug: "black-pink",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 74,
    image: ["/limelight/14.jpg"],
    price: 6000,
    category: "Limelight",
    size: ["S", "M", "L", "XL"],
    title: "Limelight",
    slug: "gray-yellow",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    qty: 1,
  },
  {
    id: 75,
    image: ["/limelight/15.jpg"],
    price: 8000,
    category: "Limelight",
    title: "Limelight",
    slug: "black-blue",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 76,
    image: ["/mariab/1.jpg"],
    price: 10000,
    category: "Maria-B",
    size: ["S", "M", "L", "XL"],
    title: "Maria B",
    slug: "long-gray-shirt",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    qty: 1,
  },
  {
    id: 77,
    image: ["/mariab/2.jpg"],
    price: 1399,
    category: "Maria-B",
    title: "Maria B",
    slug: "long-peach",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 78,
    image: ["/mariab/3.jpg"],
    price: 6000,
    title: "Maria B",
    slug: "long-pink-frock",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    category: "Maria-B",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 79,
    image: ["/mariab/4.jpg"],
    price: 7450,
    category: "Maria-B",
    title: "Maria B",
    slug: "long-peach-kameez",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 80,
    image: ["/mariab/5.jpg"],
    price: 16000,
    category: "Maria-B",
    title: "Maria B",
    slug: "long-lightgreen",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 81,
    image: ["/mariab/6.jpg"],
    price: 6500,
    category: "Maria-B",
    title: "Maria B",
    slug: "stylish-black",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 82,
    image: ["/mariab/7.jpg"],
    price: 5000,
    category: "Maria-B",
    title: "Maria B",
    slug: "long-kahi-kameez",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 83,
    image: ["/mariab/8.jpg"],
    price: 7590,
    title: "Maria B",
    slug: "long-marjanda-frock",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    category: "Maria-B",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 84,
    image: ["/mariab/9.jpg"],
    price: 4200,
    category: "Maria-B",
    title: "Maria B",
    slug: "multi-flowers",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 85,
    image: ["/mariab/10.jpg"],
    price: 5080,
    category: "Maria-B",
    title: "Maria B",
    slug: "long-blue",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 86,
    image: ["/mariab/11.jpg"],
    price: 3000,
    category: "Maria-B",
    title: "Maria B",
    slug: "dark-blue-flowers",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 87,
    image: ["/mariab/12.jpg"],
    price: 5400,
    category: "Maria-B",
    title: "Maria B",
    slug: "short-purple",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 88,
    image: ["/mariab/13.jpg"],
    price: 11390,
    title: "Maria B",
    slug: "long-kurti",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    category: "Maria-B",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 89,
    image: ["/mariab/14.jpg"],
    price: 13699,
    title: "Maria B",
    slug: "tea-pink",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    category: "Maria-B",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 90,
    image: ["/mariab/15.jpg"],
    price: 13400,
    title: "Maria B",
    slug: "long-frok",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    category: "Maria-B",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 91,
    image: ["/sanasafinaz/1.jpg"],
    price: 7399,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "white-embroidy",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 92,
    image: ["/sanasafinaz/2.jpg"],
    price: 4800,
    title: "Sana Safinaz",
    slug: "white-lightblue",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    category: "Sana-Safinaz",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 93,
    image: ["/sanasafinaz/3.jpg"],
    title: "Sana Safinaz",
    slug: "white-green",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    price: 4200,
    category: "Sana-Safinaz",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 94,
    image: ["/sanasafinaz/4.jpg"],
    price: 2500,
    title: "Sana Safinaz",
    slug: "short-kurti",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    category: "Sana-Safinaz",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 95,
    image: ["/sanasafinaz/5.jpg"],
    price: 5000,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "dark-kahi",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 96,
    image: ["/sanasafinaz/6.jpg"],
    price: 6400,
    title: "Sana Safinaz",
    slug: "dark-yellow",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    category: "Sana-Safinaz",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 97,
    image: ["/sanasafinaz/7.jpg"],
    price: 6725,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "short-darkblue",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 98,
    image: ["/sanasafinaz/8.jpg"],
    price: 4890,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "short-pink",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 99,
    image: ["/sanasafinaz/9.jpg"],
    price: 7000,
    category: "Sana-Safinaz",
    size: ["S", "M", "L", "XL"],
    title: "Sana Safinaz",
    slug: "peach-big-flowers",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    qty: 1,
  },
  {
    id: 100,
    image: ["/sanasafinaz/10.jpg"],
    price: 14050,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "white-embroided",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 101,
    image: ["/sanasafinaz/11.jpg"],
    price: 15400,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "white-long-embroidy",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 102,
    image: ["/sanasafinaz/12.jpg"],
    price: 12600,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "light-blue",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 103,
    image: ["/sanasafinaz/13.jpg"],
    price: 17000,
    title: "Sana Safinaz",
    slug: "peach-embroidy",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    category: "Sana-Safinaz",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 104,
    image: ["/sanasafinaz/14.jpg"],
    price: 19300,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "offwhite-chicken",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 105,
    image: ["/sanasafinaz/15.jpg"],
    price: 3500,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "yellow-kurti",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 106,
    image: ["/sanasafinaz/16.jpg"],
    price: 2760,
    category: "Sana-Safinaz",
    title: "Sana Safinaz",
    slug: "white-red",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 107,
    image: ["/saya/1.jpg"],
    price: 4800,
    title: "Saya",
    slug: "big-white-roses",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    category: "Saya",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 108,
    image: ["/saya/2.jpg"],
    title: "Saya",
    slug: "simple-pink",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    price: 5000,
    category: "Saya",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 109,
    image: ["/saya/3.jpg"],
    price: 10300,
    category: "Saya",
    title: "Saya",
    slug: "kahi-green",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 110,
    image: ["/saya/4.jpg"],
    price: 9900,
    title: "Saya",
    slug: "simple-blue",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    category: "Saya",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 111,
    image: ["/saya/5.jpg"],
    price: 7400,
    title: "Saya",
    slug: "lemon-green",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    category: "Saya",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 112,
    image: ["/saya/6.jpg"],
    price: 6890,
    title: "Saya",
    slug: "pink-suit",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    category: "Saya",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 113,
    image: ["/saya/7.jpg"],
    price: 8380,
    category: "Saya",
    size: ["S", "M", "L", "XL"],
    title: "Saya",
    slug: "greeen-pink",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    qty: 1,
  },
  {
    id: 114,
    image: ["/saya/8.jpg"],
    price: 5990,
    category: "Saya",
    title: "Saya",
    slug: "printed-peach",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 115,
    image: ["/saya/9.jpg"],
    price: 4500,
    category: "Saya",
    size: ["S", "M", "L", "XL"],
    title: "Saya",
    slug: "white-pinkflowers",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    qty: 1,
  },
  {
    id: 116,
    image: ["/saya/10.jpg"],
    price: 3699,
    title: "Saya",
    slug: "lightblue-pink",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    category: "Saya",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 117,
    image: ["/saya/11.jpg"],
    price: 12600,
    category: "Saya",
    title: "Saya",
    slug: "red-black-golden",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 118,
    image: ["/saya/12.jpg"],
    price: 4300,
    category: "Saya",
    title: "Saya",
    slug: "white-redflowers",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 119,
    image: ["/saya/13.jpg"],
    price: 4700,
    category: "Saya",
    title: "Saya",
    slug: "darkblue-lightblue",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 120,
    image: ["/saya/14.jpg"],
    price: 3299,
    category: "Saya",
    title: "Saya",
    slug: "multi-geometry-design",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 121,
    image: ["/best1.jpg"],
    title: "Limelight",
    description:
      "Limelight is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.It is a trendy fashion brand offering stylish, affordable clothing and accessories that blend contemporary designs with everyday comfort.",
    price: 3499,
    category: "Limelight",
    slug: "off-white",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 122,
    image: ["/best2.jpg"],
    title: "Saya",
    description:
      "Discover the perfect blend of comfort and style with Saya chic collections. Fashion-forward, affordable, and always on trend! Saya is a contemporary fashion brand offering stylish, sophisticated, and versatile clothing with a perfect blend of modern cuts and traditional elegance.",
    price: 4299,
    category: "Saya",
    slug: "lightpurple-embrodry",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 123,
    image: ["/best3.jpg"],
    title: "Maria B",
    description:
      "Indulge in luxury with Maria B exquisite designs and premium fabrics. Redefining elegance, one outfit at a time! Maria B is a renowned fashion brand offering elegant and chic designs, blending traditional craftsmanship with modern flair for timeless, sophisticated style.",
    price: 2999,
    category: "Maria-B",
    slug: "blue-multi",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 124,
    image: ["/best4.jpg"],
    title: "Alkaram",
    description:
      "Experience timeless elegance with Alkaram exquisite fabrics and designs. Dress in style, comfort, and sophistication every day! Alkaram is a premium fashion brand known for its vibrant, high-quality fabrics and elegant designs, offering a perfect blend of tradition and modernity for every occasion.",
    price: 3000,
    category: "Alkaram",
    slug: "light-purple",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 125,
    image: ["/best5.jpg"],
    title: "Junaid Jamshed",
    description:
      "Elevate your style with J. Brand where luxury meets comfort in every stitch. Discover the perfect fit for every occasion today! J. is a leading Pakistani brand known for its fusion of traditional and contemporary styles, offering high-quality apparel and accessories for every occasion.",
    price: 2499,
    category: "Junaid-Jamshed",
    slug: "short-skyblue",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
  {
    id: 126,
    image: ["/best6.jpg"],
    title: "Sana Safinaz",
    description:
      "Experience the epitome of luxury with Sana Safinaz stunning collections. Timeless designs that celebrate elegance and sophistication! Sana Safinaz is a luxury fashion brand known for its timeless elegance, intricate designs, and perfect blend of traditional craftsmanship with modern style.",
    price: 3000,
    category: "Sana-Safinaz",
    slug: "baby-pink",
    size: ["S", "M", "L", "XL"],
    qty: 1,
  },
];
